import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

import Nav from '../components/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Clerk Tweet App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" className=' bg-zinc-300'>
        <body className={`${inter.className} text-stone-900 md:mx-32`}>
          <Nav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
